name: flutter_pertama
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/landscape-1.jpg
    - assets/images/landscape-2.jpg
    - assets/images/landscape-3.jpg
    - assets/images/landscape-4.jpg
    - assets/images/landscape-5.jpg
    - assets/images/pancake.jpg
    - assets/images/animal-1.jpg
    - assets/images/animal-2.jpg
    - assets/images/animal-3.jpg
    - assets/images/animal-4.jpg
    - assets/pictures/pic-0.jpg
    - assets/pictures/pic-1.jpg
    - assets/pictures/pic-2.jpg
    - assets/pictures/pic-3.jpg
    - assets/pictures/pic-4.jpg
    - assets/pictures/pic-5.jpg
    - assets/pictures/pic-6.jpg
    - assets/pictures/pic-7.jpg
    - assets/pictures/pic-8.jpg
    - assets/pictures/pic-9.jpg
    - assets/pictures/pic-10.jpg
    - assets/pictures/pic-11.jpg
    - assets/pictures/pic-12.jpg
    - assets/pictures/pic-13.jpg
    - assets/pictures/pic-14.jpg
    - assets/pictures/pic-15.jpg
    - assets/pictures/pic-16.jpg
    - assets/pictures/pic-17.jpg
    - assets/pictures/pic-18.jpg
    - assets/pictures/pic-19.jpg
    - assets/pictures/pic-20.jpg
    - assets/pictures/pic-21.jpg
    - assets/pictures/pic-22.jpg
    - assets/pictures/pic-23.jpg
    - assets/pictures/pic-24.jpg
    - assets/pictures/pic-25.jpg
    - assets/pictures/pic-26.jpg
    - assets/pictures/pic-27.jpg
    - assets/pictures/pic-28.jpg
    - assets/pictures/pic-29.jpg
    - assets/pictures/pic-30.jpg
    - assets/pictures/pic-31.jpg
    - assets/pictures/pic-32.jpg
    - assets/pictures/pic-33.jpg
    - assets/pictures/pic-34.jpg
    - assets/pictures/pic-35.jpg
    - assets/pictures/pic-36.jpg
    - assets/pictures/pic-37.jpg
    - assets/pictures/pic-38.jpg
    - assets/pictures/pic-39.jpg
    - assets/pictures/pic-40.jpg
    - assets/pictures/pic-41.jpg
    - assets/pictures/pic-42.jpg
    - assets/pictures/pic-43.jpg
    - assets/pictures/pic-44.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
